In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import sqlite3
import dateutil.parser as parser
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
#Create Database Connection
DBName = '../Data/yelp_project.db'
conn=sqlite3.connect(DBName)
cursor = conn.cursor()

In [3]:
#Read Business Data
query = "SELECT b.business_id, r.stars, attributes, date, useful, cool, funny, postal_code FROM review r JOIN \
business b USING (business_id) WHERE CAST(postal_code AS int)>=15000 AND CAST(postal_code AS int)<15500"
business_data = pd.read_sql_query(query,conn)
business_data

business_id  stars  \
0       cnGIivYRLxpF7tBVR_JwWA      1   
1       cnGIivYRLxpF7tBVR_JwWA      5   
2       cnGIivYRLxpF7tBVR_JwWA      5   
3       cnGIivYRLxpF7tBVR_JwWA      5   
4       P3LisOj7DktgGa7C5FYpnA      1   
5       P3LisOj7DktgGa7C5FYpnA      2   
6       P3LisOj7DktgGa7C5FYpnA      3   
7       P3LisOj7DktgGa7C5FYpnA      5   
8       P3LisOj7DktgGa7C5FYpnA      5   
9       P3LisOj7DktgGa7C5FYpnA      5   
10      P3LisOj7DktgGa7C5FYpnA      5   
11      P3LisOj7DktgGa7C5FYpnA      5   
12      93otbGHE0s0m-lU1osvg9w      1   
13      93otbGHE0s0m-lU1osvg9w      1   
14      93otbGHE0s0m-lU1osvg9w      1   
15      93otbGHE0s0m-lU1osvg9w      1   
16      93otbGHE0s0m-lU1osvg9w      1   
17      93otbGHE0s0m-lU1osvg9w      1   
18      93otbGHE0s0m-lU1osvg9w      1   
19      93otbGHE0s0m-lU1osvg9w      1   
20      93otbGHE0s0m-lU1osvg9w      1   
21      93otbGHE0s0m-lU1osvg9w      1   
22      93otbGHE0s0m-lU1osvg9w      1   
23      93otbGHE0s0m-lU1osvg9w      1   
24      93otbGHE0s0m-lU1osvg9w      1   
25      93otbGHE0s0m-lU1osvg9w      1   
26      93otbGHE0s0m-lU1osvg9w      1   
27      93otbGHE0s0m-lU1osvg9w      2   
28      93otbGHE0s0m-lU1osvg9w      2   
29      93otbGHE0s0m-lU1osvg9w      2   
...                        ...    ...   
176475  VqprK2mx2d6X3fufk5y58w      5   
176476  xh_ByBcQAU40VlbeqH-YkQ      1   
176477  xh_ByBcQAU40VlbeqH-YkQ      1   
176478  xh_ByBcQAU40VlbeqH-YkQ      1   
176479  xh_ByBcQAU40VlbeqH-YkQ      3   
176480  xh_ByBcQAU40VlbeqH-YkQ      3   
176481  xh_ByBcQAU40VlbeqH-YkQ      4   
176482  xh_ByBcQAU40VlbeqH-YkQ      4   
176483  xh_ByBcQAU40VlbeqH-YkQ      4   
176484  xh_ByBcQAU40VlbeqH-YkQ      4   
176485  xh_ByBcQAU40VlbeqH-YkQ      5   
176486  xh_ByBcQAU40VlbeqH-YkQ      5   
176487  xh_ByBcQAU40VlbeqH-YkQ      5   
176488  xh_ByBcQAU40VlbeqH-YkQ      5   
176489  xh_ByBcQAU40VlbeqH-YkQ      5   
176490  xh_ByBcQAU40VlbeqH-YkQ      5   
176491  xh_ByBcQAU40VlbeqH-YkQ      5   
176492  xh_ByBcQAU40VlbeqH-YkQ      5   
176493  xh_ByBcQAU40VlbeqH-YkQ      5   
176494  xh_ByBcQAU40VlbeqH-YkQ      5   
176495  xh_ByBcQAU40VlbeqH-YkQ      5   
176496  xh_ByBcQAU40VlbeqH-YkQ      5   
176497  xh_ByBcQAU40VlbeqH-YkQ      5   
176498  xh_ByBcQAU40VlbeqH-YkQ      5   
176499  xh_ByBcQAU40VlbeqH-YkQ      5   
176500  xh_ByBcQAU40VlbeqH-YkQ      5   
176501  xh_ByBcQAU40VlbeqH-YkQ      5   
176502  wZEMd6KoSOm2hPOB2vAeNg      5   
176503  wZEMd6KoSOm2hPOB2vAeNg      5   
176504  wZEMd6KoSOm2hPOB2vAeNg      5   

                                               attributes        date  useful  \
0       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-02-01       0   
1       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-07-04       0   
2       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-07-28       0   
3       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-08-06       0   
4                    ['BusinessAcceptsCreditCards: True']  2015-09-19       4   
5                    ['BusinessAcceptsCreditCards: True']  2014-01-29       4   
6                    ['BusinessAcceptsCreditCards: True']  2016-12-05       0   
7                    ['BusinessAcceptsCreditCards: True']  2011-11-19       2   
8                    ['BusinessAcceptsCreditCards: True']  2013-10-05       0   
9                    ['BusinessAcceptsCreditCards: True']  2014-01-12       2   
10                   ['BusinessAcceptsCreditCards: True']  2015-03-20       1   
11                   ['BusinessAcceptsCreditCards: True']  2016-01-15       2   
12      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2013-09-22       1   
13      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-05-25       0   
14      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-08-10       0   
15      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-08-22       0   
16      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2015-08-22       0   
17      ['Alcohol:

In [4]:
#Split the attributes one per row
attributes_splitted = pd.concat([pd.Series(row['business_id'],row['attributes'].split(',')) for _, row in business_data.dropna().iterrows()]).reset_index()
attributes_splitted.columns = ['Attributes', 'business_id']

In [5]:
attributes_splitted

Attributes             business_id
0                     ['AcceptsInsurance: False'  cnGIivYRLxpF7tBVR_JwWA
1             'BusinessAcceptsCreditCards: True'  cnGIivYRLxpF7tBVR_JwWA
2             "BusinessParking: {'garage': False  cnGIivYRLxpF7tBVR_JwWA
3                                'street': False  cnGIivYRLxpF7tBVR_JwWA
4                             'validated': False  cnGIivYRLxpF7tBVR_JwWA
5                                    'lot': True  cnGIivYRLxpF7tBVR_JwWA
6                               'valet': False}"  cnGIivYRLxpF7tBVR_JwWA
7                      'ByAppointmentOnly: True'  cnGIivYRLxpF7tBVR_JwWA
8         "HairSpecializesIn: {'coloring': False  cnGIivYRLxpF7tBVR_JwWA
9                       'africanamerican': False  cnGIivYRLxpF7tBVR_JwWA
10                                'curly': False  cnGIivYRLxpF7tBVR_JwWA
11                                'perms': False  cnGIivYRLxpF7tBVR_JwWA
12                                 'kids': False  cnGIivYRLxpF7tBVR_JwWA
13                           'extensions': False  cnGIivYRLxpF7tBVR_JwWA
14                                'asian': False  cnGIivYRLxpF7tBVR_JwWA
15                      'straightperms': False}"  cnGIivYRLxpF7tBVR_JwWA
16                  'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA
17                    ['AcceptsInsurance: False'  cnGIivYRLxpF7tBVR_JwWA
18            'BusinessAcceptsCreditCards: True'  cnGIivYRLxpF7tBVR_JwWA
19            "BusinessParking: {'garage': False  cnGIivYRLxpF7tBVR_JwWA
20                               'street': False  cnGIivYRLxpF7tBVR_JwWA
21                            'validated': False  cnGIivYRLxpF7tBVR_JwWA
22                                   'lot': True  cnGIivYRLxpF7tBVR_JwWA
23                              'valet': False}"  cnGIivYRLxpF7tBVR_JwWA
24                     'ByAppointmentOnly: True'  cnGIivYRLxpF7tBVR_JwWA
25        "HairSpecializesIn: {'coloring': False  cnGIivYRLxpF7tBVR_JwWA
26                      'africanamerican': False  cnGIivYRLxpF7tBVR_JwWA
27                                'curly': False  cnGIivYRLxpF7tBVR_JwWA
28                                'perms': False  cnGIivYRLxpF7tBVR_JwWA
29                                 'kids': False  cnGIivYRLxpF7tBVR_JwWA
...                                          ...                     ...
5315834               ['AcceptsInsurance: False'  VqprK2mx2d6X3fufk5y58w
5315835                      'BikeParking: True'  VqprK2mx2d6X3fufk5y58w
5315836       'BusinessAcceptsCreditCards: True'  VqprK2mx2d6X3fufk5y58w
5315837       "BusinessParking: {'garage': False  VqprK2mx2d6X3fufk5y58w
5315838                          'street': False  VqprK2mx2d6X3fufk5y58w
5315839                       'validated': False  VqprK2mx2d6X3fufk5y58w
5315840                             'lot': False  VqprK2mx2d6X3fufk5y58w
5315841                         'valet': False}"  VqprK2mx2d6X3fufk5y58w
5315842                'ByAppointmentOnly: True'  VqprK2mx2d6X3fufk5y58w
5315843             'RestaurantsPriceRange2: 2']  VqprK2mx2d6X3fufk5y58w
5315844               ['AcceptsInsurance: False'  VqprK2mx2d6X3fufk5y58w
5315845                      'BikeParking: True'  VqprK2mx2d6X3fufk5y58w
5315846       'BusinessAcceptsCreditCards: True'  VqprK2mx2d6X3fufk5y58w
5315847       "BusinessParking: {'garage': False  VqprK2mx2d6X3fufk5y58w
5315848                          'street': False  VqprK2mx2d6X3fufk5y58w
5315849                       'validated': False  VqprK2mx2d6X3fufk5y58w
5315850                             'lot': False  VqprK2mx2d6X3fufk5y58w
5315851                         'valet': False}"  VqprK2mx2d6X3fufk5y58w
5315852                'ByAppointmentOnly: True'  VqprK2mx2d6X3fufk5y58w
5315853             'RestaurantsPriceRange2: 2']  VqprK2mx2d6X3fufk5y58w
5315854               ['AcceptsInsurance: False'  VqprK2mx2d6X3fufk5y58w
5315855                      'BikeParking: True'  VqprK2mx2d6X3fufk5y58w
5315856       'BusinessAcceptsCreditCards: True'  VqprK2mx2d6X3fufk5y58w
5315857       "Business

In [6]:
#Get Restaurants with price
restprice = attributes_splitted[attributes_splitted.Attributes.str.contains("restaurantspricerange", case=False)].reset_index()
restprice

index                     Attributes             business_id
0            16   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA
1            33   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA
2            50   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA
3            67   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA
4           124    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
5           179    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
6           234    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
7           289    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
8           344    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
9           399    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
10          454    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
11          509    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
12          564    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
13          619    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
14          674    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
15          729    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
16          784    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
17          839    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
18          894    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
19          949    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
20         1004    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
21         1059    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
22         1114    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
23         1169    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
24         1224    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
25         1279    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
26         1334    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
27         1389    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
28         1444    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
29         1499    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w
...         ...                            ...                     ...
156005  5314982    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156006  5315019    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156007  5315056    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156008  5315093    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156009  5315130    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156010  5315167    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156011  5315204    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156012  5315241    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156013  5315278    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156014  5315315    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156015  5315352    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156016  5315389    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156017  5315426    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156018  5315463    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156019  5315500    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156020  5315537    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156021  5315574    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156022  5315611    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156023  5315648    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156024  5315685    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156025  5315722    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156026  5315759    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w
156027  5315777    'RestaurantsPriceRange2: 1'  ZZ8sAXHb0gX-c81Ea1M3OQ
156028  5315792    'RestaurantsPriceRange2: 1'  ZZ8sAXHb0gX-c81Ea1M3OQ
156029  5315807    'RestaurantsPri

In [98]:
#Extract price range and remove non-numerical characters
restprice['Price'] = [ pd.to_numeric(re.sub(r"[\[\]' ]", "", r.split(":")[1])) for r in restprice.Attributes]
restprice

index                     Attributes             business_id  Price
0            16   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA      3
1            33   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA      3
2            50   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA      3
3            67   'RestaurantsPriceRange2: 3']  cnGIivYRLxpF7tBVR_JwWA      3
4           124    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
5           179    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
6           234    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
7           289    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
8           344    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
9           399    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
10          454    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
11          509    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
12          564    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
13          619    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
14          674    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
15          729    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
16          784    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
17          839    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
18          894    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
19          949    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
20         1004    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
21         1059    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
22         1114    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
23         1169    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
24         1224    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
25         1279    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
26         1334    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
27         1389    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
28         1444    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
29         1499    'RestaurantsPriceRange2: 2'  93otbGHE0s0m-lU1osvg9w      2
...         ...                            ...                     ...    ...
156005  5314982    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156006  5315019    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156007  5315056    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156008  5315093    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156009  5315130    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156010  5315167    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156011  5315204    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156012  5315241    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156013  5315278    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156014  5315315    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156015  5315352    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156016  5315389    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156017  5315426    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156018  5315463    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156019  5315500    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156020  5315537    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156021  5315574    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156022  5315611    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156023  5315648    'RestaurantsPriceRange2: 2'  7ummB6k1hmUgljgrzevM2w      2
156024  5315685    'RestaurantsP

In [99]:
business_price = restprice[['business_id', 'Price']]
business_price

business_id  Price
0       cnGIivYRLxpF7tBVR_JwWA      3
1       cnGIivYRLxpF7tBVR_JwWA      3
2       cnGIivYRLxpF7tBVR_JwWA      3
3       cnGIivYRLxpF7tBVR_JwWA      3
4       93otbGHE0s0m-lU1osvg9w      2
5       93otbGHE0s0m-lU1osvg9w      2
6       93otbGHE0s0m-lU1osvg9w      2
7       93otbGHE0s0m-lU1osvg9w      2
8       93otbGHE0s0m-lU1osvg9w      2
9       93otbGHE0s0m-lU1osvg9w      2
10      93otbGHE0s0m-lU1osvg9w      2
11      93otbGHE0s0m-lU1osvg9w      2
12      93otbGHE0s0m-lU1osvg9w      2
13      93otbGHE0s0m-lU1osvg9w      2
14      93otbGHE0s0m-lU1osvg9w      2
15      93otbGHE0s0m-lU1osvg9w      2
16      93otbGHE0s0m-lU1osvg9w      2
17      93otbGHE0s0m-lU1osvg9w      2
18      93otbGHE0s0m-lU1osvg9w      2
19      93otbGHE0s0m-lU1osvg9w      2
20      93otbGHE0s0m-lU1osvg9w      2
21      93otbGHE0s0m-lU1osvg9w      2
22      93otbGHE0s0m-lU1osvg9w      2
23      93otbGHE0s0m-lU1osvg9w      2
24      93otbGHE0s0m-lU1osvg9w      2
25      93otbGHE0s0m-lU1osvg9w      2
26      93otbGHE0s0m-lU1osvg9w      2
27      93otbGHE0s0m-lU1osvg9w      2
28      93otbGHE0s0m-lU1osvg9w      2
29      93otbGHE0s0m-lU1osvg9w      2
...                        ...    ...
156005  7ummB6k1hmUgljgrzevM2w      2
156006  7ummB6k1hmUgljgrzevM2w      2
156007  7ummB6k1hmUgljgrzevM2w      2
156008  7ummB6k1hmUgljgrzevM2w      2
156009  7ummB6k1hmUgljgrzevM2w      2
156010  7ummB6k1hmUgljgrzevM2w      2
156011  7ummB6k1hmUgljgrzevM2w      2
156012  7ummB6k1hmUgljgrzevM2w      2
156013  7ummB6k1hmUgljgrzevM2w      2
156014  7ummB6k1hmUgljgrzevM2w      2
156015  7ummB6k1hmUgljgrzevM2w      2
156016  7ummB6k1hmUgljgrzevM2w      2
156017  7ummB6k1hmUgljgrzevM2w      2
156018  7ummB6k1hmUgljgrzevM2w      2
156019  7ummB6k1hmUgljgrzevM2w      2
156020  7ummB6k1hmUgljgrzevM2w      2
156021  7ummB6k1hmUgljgrzevM2w      2
156022  7ummB6k1hmUgljgrzevM2w      2
156023  7ummB6k1hmUgljgrzevM2w      2
156024  7ummB6k1hmUgljgrzevM2w      2
156025  7ummB6k1hmUgljgrzevM2w      2
156026  7ummB6k1hmUgljgrzevM2w      2
156027  ZZ8sAXHb0gX-c81Ea1M3OQ      1
156028  ZZ8sAXHb0gX-c81Ea1M3OQ      1
156029  ZZ8sAXHb0gX-c81Ea1M3OQ      1
156030  VqprK2mx2d6X3fufk5y58w      2
156031  VqprK2mx2d6X3fufk5y58w      2
156032  VqprK2mx2d6X3fufk5y58w      2
156033  VqprK2mx2d6X3fufk5y58w      2
156034  VqprK2mx2d6X3fufk5y58w      2

[156035 rows x 2 columns]

In [116]:
#Left Join of both df
business_data_Price = business_data.join(business_price, how = 'left', rsuffix='_bp')

In [121]:
years=[pd.to_datetime(row['date']).year for _, row in business_data_Price.iterrows()]

In [122]:
len(years)

176505

In [125]:
business_data_Price['Years'] = years
business_data_Price

business_id  stars  \
0       cnGIivYRLxpF7tBVR_JwWA      1   
1       cnGIivYRLxpF7tBVR_JwWA      5   
2       cnGIivYRLxpF7tBVR_JwWA      5   
3       cnGIivYRLxpF7tBVR_JwWA      5   
4       P3LisOj7DktgGa7C5FYpnA      1   
5       P3LisOj7DktgGa7C5FYpnA      2   
6       P3LisOj7DktgGa7C5FYpnA      3   
7       P3LisOj7DktgGa7C5FYpnA      5   
8       P3LisOj7DktgGa7C5FYpnA      5   
9       P3LisOj7DktgGa7C5FYpnA      5   
10      P3LisOj7DktgGa7C5FYpnA      5   
11      P3LisOj7DktgGa7C5FYpnA      5   
12      93otbGHE0s0m-lU1osvg9w      1   
13      93otbGHE0s0m-lU1osvg9w      1   
14      93otbGHE0s0m-lU1osvg9w      1   
15      93otbGHE0s0m-lU1osvg9w      1   
16      93otbGHE0s0m-lU1osvg9w      1   
17      93otbGHE0s0m-lU1osvg9w      1   
18      93otbGHE0s0m-lU1osvg9w      1   
19      93otbGHE0s0m-lU1osvg9w      1   
20      93otbGHE0s0m-lU1osvg9w      1   
21      93otbGHE0s0m-lU1osvg9w      1   
22      93otbGHE0s0m-lU1osvg9w      1   
23      93otbGHE0s0m-lU1osvg9w      1   
24      93otbGHE0s0m-lU1osvg9w      1   
25      93otbGHE0s0m-lU1osvg9w      1   
26      93otbGHE0s0m-lU1osvg9w      1   
27      93otbGHE0s0m-lU1osvg9w      2   
28      93otbGHE0s0m-lU1osvg9w      2   
29      93otbGHE0s0m-lU1osvg9w      2   
...                        ...    ...   
176475  VqprK2mx2d6X3fufk5y58w      5   
176476  xh_ByBcQAU40VlbeqH-YkQ      1   
176477  xh_ByBcQAU40VlbeqH-YkQ      1   
176478  xh_ByBcQAU40VlbeqH-YkQ      1   
176479  xh_ByBcQAU40VlbeqH-YkQ      3   
176480  xh_ByBcQAU40VlbeqH-YkQ      3   
176481  xh_ByBcQAU40VlbeqH-YkQ      4   
176482  xh_ByBcQAU40VlbeqH-YkQ      4   
176483  xh_ByBcQAU40VlbeqH-YkQ      4   
176484  xh_ByBcQAU40VlbeqH-YkQ      4   
176485  xh_ByBcQAU40VlbeqH-YkQ      5   
176486  xh_ByBcQAU40VlbeqH-YkQ      5   
176487  xh_ByBcQAU40VlbeqH-YkQ      5   
176488  xh_ByBcQAU40VlbeqH-YkQ      5   
176489  xh_ByBcQAU40VlbeqH-YkQ      5   
176490  xh_ByBcQAU40VlbeqH-YkQ      5   
176491  xh_ByBcQAU40VlbeqH-YkQ      5   
176492  xh_ByBcQAU40VlbeqH-YkQ      5   
176493  xh_ByBcQAU40VlbeqH-YkQ      5   
176494  xh_ByBcQAU40VlbeqH-YkQ      5   
176495  xh_ByBcQAU40VlbeqH-YkQ      5   
176496  xh_ByBcQAU40VlbeqH-YkQ      5   
176497  xh_ByBcQAU40VlbeqH-YkQ      5   
176498  xh_ByBcQAU40VlbeqH-YkQ      5   
176499  xh_ByBcQAU40VlbeqH-YkQ      5   
176500  xh_ByBcQAU40VlbeqH-YkQ      5   
176501  xh_ByBcQAU40VlbeqH-YkQ      5   
176502  wZEMd6KoSOm2hPOB2vAeNg      5   
176503  wZEMd6KoSOm2hPOB2vAeNg      5   
176504  wZEMd6KoSOm2hPOB2vAeNg      5   

                                               attributes        date  useful  \
0       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-02-01       0   
1       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-07-04       0   
2       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-07-28       0   
3       ['AcceptsInsurance: False', 'BusinessAcceptsCr...  2016-08-06       0   
4                    ['BusinessAcceptsCreditCards: True']  2015-09-19       4   
5                    ['BusinessAcceptsCreditCards: True']  2014-01-29       4   
6                    ['BusinessAcceptsCreditCards: True']  2016-12-05       0   
7                    ['BusinessAcceptsCreditCards: True']  2011-11-19       2   
8                    ['BusinessAcceptsCreditCards: True']  2013-10-05       0   
9                    ['BusinessAcceptsCreditCards: True']  2014-01-12       2   
10                   ['BusinessAcceptsCreditCards: True']  2015-03-20       1   
11                   ['BusinessAcceptsCreditCards: True']  2016-01-15       2   
12      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2013-09-22       1   
13      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-05-25       0   
14      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-08-10       0   
15      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2014-08-22       0   
16      ['Alcohol: full_bar', "Ambience: {'romantic': ...  2015-08-22       0   
17      ['Alcohol:

In [134]:
zip_matrix = business_data_Price[['postal_code', 'Years', 'stars', 'useful', 'funny', 'cool', 'Price']]
stars = zip_matrix.stars
zip_matrix = pd.get_dummies(zip_matrix, columns = ["stars"])
zip_matrix['stars'] = stars
zip_matrix

postal_code  Years  useful  funny  cool  Price  stars_1  stars_2  \
0            15071   2016       0      0     0    3.0      1.0      0.0   
1            15071   2016       0      0     0    3.0      0.0      0.0   
2            15071   2016       0      0     0    3.0      0.0      0.0   
3            15071   2016       0      0     0    3.0      0.0      0.0   
4            15237   2015       4      0     0    2.0      1.0      0.0   
5            15237   2014       4      0     1    2.0      0.0      1.0   
6            15237   2016       0      0     0    2.0      0.0      0.0   
7            15237   2011       2      0     0    2.0      0.0      0.0   
8            15237   2013       0      0     0    2.0      0.0      0.0   
9            15237   2014       2      0     0    2.0      0.0      0.0   
10           15237   2015       1      0     0    2.0      0.0      0.0   
11           15237   2016       2      0     0    2.0      0.0      0.0   
12           15212   2013       1      0     0    2.0      1.0      0.0   
13           15212   2014       0      0     0    2.0      1.0      0.0   
14           15212   2014       0      0     0    2.0      1.0      0.0   
15           15212   2014       0      0     0    2.0      1.0      0.0   
16           15212   2015       0      0     0    2.0      1.0      0.0   
17           15212   2015       1      0     0    2.0      1.0      0.0   
18           15212   2015       0      0     0    2.0      1.0      0.0   
19           15212   2015       0      0     0    2.0      1.0      0.0   
20           15212   2015       0      0     0    2.0      1.0      0.0   
21           15212   2016       0      0     0    2.0      1.0      0.0   
22           15212   2016       0      0     0    2.0      1.0      0.0   
23           15212   2016       0      0     0    2.0      1.0      0.0   
24           15212   2016       0      0     0    2.0      1.0      0.0   
25           15212   2016       0      0     0    2.0      1.0      0.0   
26           15212   2016       1      0     0    2.0      1.0      0.0   
27           15212   2012       2      0     0    2.0      0.0      1.0   
28           15212   2012       1      0     0    2.0      0.0      1.0   
29           15212   2013       0      0     0    2.0      0.0      1.0   
...            ...    ...     ...    ...   ...    ...      ...      ...   
176475       15237   2016       0      0     0    NaN      0.0      0.0   
176476       15237   2013       9      0     0    NaN      1.0      0.0   
176477       15237   2016       5      0     0    NaN      1.0      0.0   
176478       15237   2016       1      0     0    NaN      1.0      0.0   
176479       15237   2015       3      0     1    NaN      0.0      0.0   
176480       15237   2016       0      0     0    NaN      0.0      0.0   
176481       15237   2014       1      0     0    NaN      0.0      0.0   
176482       15237   2015       5      0     0    NaN      0.0      0.0   
176483       15237   2015       2      0     0    NaN      0.0      0.0   
176484       15237   2015       2      0     0    NaN      0.0      0.0   
176485       15237   2010       3      0     0    NaN      0.0      0.0   
176486       15237   2013       4      0     1    NaN      0.0      0.0   
176487       15237   2014       0      0     0    NaN      0.0      0.0   
176488       15237   2015       1      0     0    NaN      0.0      0.0   
176489       15237   2015       0      0     0    NaN      0.0      0.0   
176490       15237   2015       0      0     0    NaN      0.0      0.0   
176491       15237   2015       0      0     0    NaN      0.0      0.0   
176492       15237   2015       1      0     0    NaN      0.0      0.0   
176493       15237   2015       1      0     0    NaN      0.0      0.0   
176494       15237   2015       0      0     0    NaN      0.0      0.0   
176495       15237   2015       0      0     0    NaN      0.0      0.0   
176496       15237   2015       

In [138]:
zip_aggregated = zip_matrix.groupby(['postal_code', 'Years']).agg(pd.Series.mean)
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.500000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.500000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.066667  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  2.000000  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.217391  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.311111  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  1.949153  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.333333  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.750000  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.703704  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.697368  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.681159  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.884615  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.812734  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.815348  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.785714  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.870968  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.949153  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.875000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.695652  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.529412  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

pandas.core.frame.DataFrame

In [143]:
#business_price_zip = business_price.join(business_data, how = "inner", rsuffix="_bp")
business_price_zip = business_data_Price[['business_id','Price', 'postal_code', 'Years']].drop_duplicates()
price_zip = business_price_zip[['postal_code', 'Price', 'Years']]
price_zip

postal_code  Price  Years
0            15071    3.0   2016
4            15237    2.0   2015
5            15237    2.0   2014
6            15237    2.0   2016
7            15237    2.0   2011
8            15237    2.0   2013
12           15212    2.0   2013
13           15212    2.0   2014
16           15212    2.0   2015
21           15212    2.0   2016
27           15212    2.0   2012
43           15212    2.0   2010
44           15212    2.0   2011
95           15212    2.0   2017
106          15212    4.0   2016
107          15212    4.0   2011
108          15212    4.0   2013
114          15220    2.0   2015
115          15220    2.0   2016
119          15223    1.0   2014
121          15223    1.0   2015
124          15223    1.0   2016
127          15223    1.0   2012
133          15223    1.0   2013
140          15223    1.0   2017
142          15223    1.0   2011
154          15223    1.0   2010
157          15213    1.0   2016
158          15213    1.0   2014
159          15213    1.0   2015
...            ...    ...    ...
176404       15108    NaN   2016
176405       15108    NaN   2010
176413       15108    NaN   2014
176415       15108    NaN   2015
176418       15108    NaN   2008
176419       15317    NaN   2016
176420       15317    NaN   2013
176422       15317    NaN   2010
176423       15317    NaN   2011
176424       15317    NaN   2012
176425       15317    NaN   2015
176436       15317    NaN   2009
176441       15317    NaN   2014
176464       15317    NaN   2016
176465       15317    NaN   2012
176466       15317    NaN   2014
176467       15237    NaN   2011
176468       15237    NaN   2012
176469       15237    NaN   2013
176470       15237    NaN   2016
176471       15237    NaN   2014
176472       15237    NaN   2015
176474       15237    NaN   2016
176476       15237    NaN   2013
176477       15237    NaN   2016
176479       15237    NaN   2015
176481       15237    NaN   2014
176485       15237    NaN   2010
176502       15116    NaN   2013
176504       15116    NaN   2015

[38406 rows x 3 columns]

In [144]:
average_price_zip = price_zip.groupby(['postal_code','Years']).agg(pd.Series.mean)

In [145]:
average_price_zip

Price
postal_code Years          
15003       2008   3.000000
            2009   2.000000
            2010   2.400000
            2011   2.400000
            2012   2.111111
            2013   1.888889
            2014   2.071429
            2015   2.076923
            2016   2.117647
            2017   2.666667
15009       2014   2.000000
            2015   2.000000
            2016   2.000000
15012       2015   1.000000
15015       2011   2.000000
            2012   1.500000
            2013   2.000000
            2014   1.000000
            2015   2.000000
            2016   1.000000
15017       2007   1.750000
            2008   1.500000
            2009   1.818182
            2010   1.800000
            2011   1.650000
            2012   1.682540
            2013   1.814286
            2014   1.773810
            2015   1.773585
            2016   1.750000
...                     ...
15321       2014   2.000000
            2015   1.600000
            2016   1.714286
            2017   2.000000
15332       2006   2.000000
            2010   2.000000
            2011   2.000000
            2012   2.000000
            2013   1.500000
            2014   1.750000
            2015   1.666667
            2016   1.571429
            2017   2.000000
15339       2011   2.000000
            2012   2.000000
            2013   2.000000
            2014   2.000000
            2015   2.000000
            2016   2.000000
15342       2011   1.666667
            2012   1.000000
            2013   1.250000
            2014   1.250000
            2015   1.833333
            2016   1.833333
15367       2012   1.000000
            2013   1.500000
            2014   2.000000
            2015   1.500000
            2016   1.500000

[1030 rows x 1 columns]

In [146]:
zip_aggregated['Price'] = average_price_zip

In [147]:
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [166]:
average_reviews_zip = business_data_Price.groupby(['postal_code','Years']).agg(pd.Series.count)
average_reviews_zip = average_reviews_zip['business_id']

business_id  stars  attributes  date  useful  cool  funny  \
postal_code Years                                                              
15003       2008             2      2           2     2       2     2      2   
            2009             2      2           2     2       2     2      2   
            2010             8      8           8     8       8     8      8   
            2011            15     15          15    15      15    15     15   
            2012            20     20          18    20      20    20     20   
            2013            25     25          23    25      25    25     25   
            2014            34     34          30    34      34    34     34   
            2015            61     61          56    61      61    61     61   
            2016            72     72          71    72      72    72     72   
            2017             4      4           4     4       4     4      4   
15009       2014             1      1           0     1       1     1      1   
            2015             1      1           0     1       1     1      1   
            2016             1      1           0     1       1     1      1   
15012       2015             3      3           3     3       3     3      3   
15015       2011             1      1           1     1       1     1      1   
            2012             2      2           2     2       2     2      2   
            2013             1      1           1     1       1     1      1   
            2014             1      1           1     1       1     1      1   
            2015             1      1           1     1       1     1      1   
            2016             2      2           2     2       2     2      2   
15017       2007             4      4           4     4       4     4      4   
            2008             3      3           3     3       3     3      3   
            2009            12     12          12    12      12    12     12   
            2010            27     27          26    27      27    27     27   
            2011            76     76          75    76      76    76     76   
            2012           138    138         137   138     138   138    138   
            2013           234    234         232   234     234   234    234   
            2014           267    267         261   267     267   267    267   
            2015           417    417         406   417     417   417    417   
            2016           602    602         579   602     602   602    602   
...                        ...    ...         ...   ...     ...   ...    ...   
15321       2014            26     26          26    26      26    26     26   
            2015            31     31          31    31      31    31     31   
            2016            59     59          59    59      59    59     59   
            2017             1      1           1     1       1     1      1   
15332       2006             1      1           1     1       1     1      1   
            2010             1      1           1     1       1     1      1   
            2011             2      2           2     2       2     2      2   
            2012             7      7           7     7       7     7      7   
            2013             8      8           8     8       8     8      8   
            2014            16     16          16    16      16    16     16   
            2015            25     25          25    25      25    25     25   
            2016            18     18          18    18      18    18     18   
            2017             1      1           1     1       1     1      1   
15339       2011             2      2           2     2       2     2      2   
            2012             1      1           1     1       1     1      1   
            2013             2      2           2     2       2     2      2   
            2014             1      1           1     1       1     1      1   
            2015   

In [200]:
review_byzip = business_data_Price.groupby(['postal_code', 'Years']).count()

In [199]:
total_reviews = business_data_Price.groupby(['Years']).count().business_id
total_reviews

31

In [212]:
review_byzip = review_byzip.reset_index()[['postal_code','Years','business_id']]
review_byzip

postal_code  Years  business_id
0          15003   2008            2
1          15003   2009            2
2          15003   2010            8
3          15003   2011           15
4          15003   2012           20
5          15003   2013           25
6          15003   2014           34
7          15003   2015           61
8          15003   2016           72
9          15003   2017            4
10         15009   2014            1
11         15009   2015            1
12         15009   2016            1
13         15012   2015            3
14         15015   2011            1
15         15015   2012            2
16         15015   2013            1
17         15015   2014            1
18         15015   2015            1
19         15015   2016            2
20         15017   2007            4
21         15017   2008            3
22         15017   2009           12
23         15017   2010           27
24         15017   2011           76
25         15017   2012          138
26         15017   2013          234
27         15017   2014          267
28         15017   2015          417
29         15017   2016          602
...          ...    ...          ...
1000       15321   2014           26
1001       15321   2015           31
1002       15321   2016           59
1003       15321   2017            1
1004       15332   2006            1
1005       15332   2010            1
1006       15332   2011            2
1007       15332   2012            7
1008       15332   2013            8
1009       15332   2014           16
1010       15332   2015           25
1011       15332   2016           18
1012       15332   2017            1
1013       15339   2011            2
1014       15339   2012            1
1015       15339   2013            2
1016       15339   2014            1
1017       15339   2015            1
1018       15339   2016            6
1019       15342   2011            4
1020       15342   2012            9
1021       15342   2013           13
1022       15342   2014            8
1023       15342   2015           14
1024       15342   2016           10
1025       15367   2012            3
1026       15367   2013            8
1027       15367   2014           10
1028       15367   2015           11
1029       15367   2016           17

[1030 rows x 3 columns]

In [217]:
prop_reviews = [ float(review_byzip.ix[i]['business_id'])/total_reviews[review_byzip.ix[i]['Years']] for i in range(len(review_byzip))]

In [219]:
zip_aggregated['reviews_perc'] = prop_reviews

In [220]:
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [249]:
flatten_zip = zip_aggregated.reset_index()
pd.to_numeric(flatten_zip[(flatten_zip['postal_code']=='15232')&(flatten_zip['Years']==2007)].stars)

791    3.923077
Name: stars, dtype: float64

In [253]:
avg_review_prev1 = [flatten_zip[(flatten_zip['postal_code']==flatten_zip.ix[i]['postal_code'])&(flatten_zip['Years']==(flatten_zip.ix[i]['Years']-1))]['stars'].values for i in range(len(flatten_zip))]

In [260]:
zip_aggregated['prev_stars'] = avg_review_prev1
zip_aggregated['prev_stars'] = zip_aggregated['prev_stars'].str.get(0)
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [261]:
#save to pickle
import pickle
output_file = open("Feature_Matrix_onlyYelp.dat","wb")
pickle.dump(zip_aggregated, output_file)
output_file.close()

In [264]:
#Integrate Zillow
zip_price = pd.read_csv("../Data/Zip_MedianValuePerSqft_AllHomes.csv")

#Select only Pittsburgh
pittsburgh_data_price = zip_price[(zip_price.RegionName>=15000)&(zip_price.RegionName<15500)]

#Select the RegionName and the columns with year
pittsburgh_data_byYear = pd.concat([pittsburgh_data_price.ix[:,1], pittsburgh_data_price[pittsburgh_data_price.columns[7:]]], axis = 1)

#Melt the dataframe to transform the columns into rows
flat_zip = pd.melt(pittsburgh_data_byYear, id_vars="RegionName", var_name="Date", value_name="MedSqft")
flat_zip

RegionName     Date  MedSqft
0           15301  1996-04     54.0
1           15237  1996-04     69.0
2           15108  1996-04     65.0
3           15068  1996-04     56.0
4           15235  1996-04     47.0
5           15317  1996-04     68.0
6           15221  1996-04     37.0
7           15206  1996-04     33.0
8           15401  1996-04     40.0
9           15001  1996-04     59.0
10          15212  1996-04     32.0
11          15236  1996-04     63.0
12          15146  1996-04     57.0
13          15227  1996-04     53.0
14          15102  1996-04     64.0
15          15217  1996-04     60.0
16          15010  1996-04     53.0
17          15213  1996-04      NaN
18          15210  1996-04     27.0
19          15205  1996-04     48.0
20          15216  1996-04     42.0
21          15044  1996-04     69.0
22          15202  1996-04     45.0
23          15101  1996-04     68.0
24          15136  1996-04     50.0
25          15132  1996-04     27.0
26          15106  1996-04     50.0
27          15122  1996-04     47.0
28          15120  1996-04     36.0
29          15090  1996-04     78.0
...           ...      ...      ...
37369       15027  2017-02    116.0
37370       15050  2017-02    131.0
37371       15142  2017-02    176.0
37372       15458  2017-02     70.0
37373       15486  2017-02    100.0
37374       15468  2017-02     55.0
37375       15438  2017-02     67.0
37376       15442  2017-02     54.0
37377       15437  2017-02    114.0
37378       15474  2017-02     58.0
37379       15034  2017-02     58.0
37380       15469  2017-02     97.0
37381       15479  2017-02     91.0
37382       15322  2017-02     67.0
37383       15043  2017-02    130.0
37384       15333  2017-02     88.0
37385       15480  2017-02     87.0
37386       15423  2017-02     85.0
37387       15360  2017-02    115.0
37388       15428  2017-02     78.0
37389       15321  2017-02    128.0
37390       15055  2017-02    114.0
37391       15019  2017-02    100.0
37392       15376  2017-02    100.0
37393       15345  2017-02     61.0
37394       15459  2017-02     97.0
37395       15340  2017-02    108.0
37396       15056  2017-02     76.0
37397       15015  2017-02    149.0
37398       15427  2017-02     70.0

[37399 rows x 3 columns]

In [265]:
#Extract only the years
years = [flat_zip.Date.ix[i].split('-')[0] for i in range(len(flat_zip))]

#Add to df
flat_zip['Years'] = years

#Select only these columns
flat_zip = flat_zip[['RegionName', 'Years', 'MedSqft']]

#Group by and aggregate by median
med_zip = flat_zip.groupby(['RegionName', 'Years']).median()

#Flatten the table
med_zip = med_zip.reset_index()
med_zip

RegionName Years  MedSqft
0          15001  1996     61.0
1          15001  1997     62.0
2          15001  1998     65.0
3          15001  1999     67.0
4          15001  2000     69.0
5          15001  2001     73.0
6          15001  2002     75.5
7          15001  2003     76.5
8          15001  2004     81.0
9          15001  2005     84.5
10         15001  2006     85.0
11         15001  2007     84.0
12         15001  2008     87.0
13         15001  2009     81.5
14         15001  2010     86.0
15         15001  2011     86.0
16         15001  2012     87.0
17         15001  2013     90.5
18         15001  2014     93.0
19         15001  2015     94.0
20         15001  2016    102.5
21         15001  2017    103.0
22         15003  1996     41.0
23         15003  1997     42.0
24         15003  1998     43.0
25         15003  1999     46.0
26         15003  2000     47.0
27         15003  2001     50.0
28         15003  2002     51.0
29         15003  2003     51.0
...          ...   ...      ...
3248       15480  2010     69.0
3249       15480  2011     70.5
3250       15480  2012     74.0
3251       15480  2013     75.5
3252       15480  2014     73.5
3253       15480  2015     75.5
3254       15480  2016     80.5
3255       15480  2017     85.5
3256       15486  1996     43.0
3257       15486  1997     48.0
3258       15486  1998     51.0
3259       15486  1999     51.0
3260       15486  2000     53.0
3261       15486  2001     56.0
3262       15486  2002     58.5
3263       15486  2003     64.0
3264       15486  2004     67.5
3265       15486  2005     70.0
3266       15486  2006     70.0
3267       15486  2007     69.0
3268       15486  2008     67.0
3269       15486  2009     69.5
3270       15486  2010     76.5
3271       15486  2011     79.0
3272       15486  2012     82.0
3273       15486  2013     84.0
3274       15486  2014     82.5
3275       15486  2015     87.5
3276       15486  2016     92.0
3277       15486  2017     98.0

[3278 rows x 3 columns]

In [287]:
Med_price_sqft = [med_zip[(med_zip['RegionName']==int(flatten_zip.ix[i]['postal_code']))&(med_zip['Years']==str(flatten_zip.ix[i]['Years']))]['MedSqft'].values for i in range(len(flatten_zip))]

In [288]:
Med_price_sqft

[array([ 57.]),
 array([ 55.5]),
 array([ 57.5]),
 array([ 54.]),
 array([ 55.5]),
 array([ 57.]),
 array([ 57.]),
 array([ 58.]),
 array([ 65.]),
 array([ 66.]),
 array([ 104.5]),
 array([ 111.]),
 array([ 116.]),
 array([ 75.5]),
 array([ 117.]),
 array([ 115.5]),
 array([ 119.]),
 array([ 126.5]),
 array([ 133.]),
 array([ 143.5]),
 array([ 96.]),
 array([ 94.]),
 array([ 93.]),
 array([ 97.]),
 array([ 98.]),
 array([ 98.]),
 array([ 101.]),
 array([ 104.]),
 array([ 109.5]),
 array([ 115.5]),
 array([ 119.]),
 array([], dtype=float64),
 array([ 91.]),
 array([ 90.5]),
 array([ 91.]),
 array([ 92.]),
 array([ 96.5]),
 array([ 99.]),
 array([ 100.]),
 array([ 102.5]),
 array([ 54.5]),
 array([ 53.]),
 array([ 55.]),
 array([ 54.]),
 array([ 54.]),
 array([ 54.]),
 array([ 57.]),
 array([ 63.]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 a

In [289]:
zip_aggregated['MedPrice_sqft'] = Med_price_sqft
zip_aggregated['MedPrice_sqft'] = zip_aggregated['MedPrice_sqft'].str.get(0)
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [291]:
zip_aggregated.columns = [u'useful', u'funny', u'cool', u'Price', u'stars_1', u'stars_2',
       u'stars_3', u'stars_4', u'stars_5', u'stars', u'reviews_perc',
       u'prev_stars', u'MedPrice_sqft(t)']

In [292]:
zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [293]:
#For t=t-1
t=-1
Med_price_sqft_tminus1 = [med_zip[(med_zip['RegionName']==int(flatten_zip.ix[i]['postal_code']))&(med_zip['Years']==str(flatten_zip.ix[i]['Years']+t))]['MedSqft'].values for i in range(len(flatten_zip))]

In [294]:
#For t=t-2
t=-2
Med_price_sqft_tminus2 = [med_zip[(med_zip['RegionName']==int(flatten_zip.ix[i]['postal_code']))&(med_zip['Years']==str(flatten_zip.ix[i]['Years']+t))]['MedSqft'].values for i in range(len(flatten_zip))]

In [295]:
#For t=t+1
t=1
Med_price_sqft_tplus1 = [med_zip[(med_zip['RegionName']==int(flatten_zip.ix[i]['postal_code']))&(med_zip['Years']==str(flatten_zip.ix[i]['Years']+t))]['MedSqft'].values for i in range(len(flatten_zip))]

In [300]:
zip_aggregated['MedPrice_sqft_tminus1'] = Med_price_sqft_tminus1
zip_aggregated['MedPrice_sqft_tminus1'] = zip_aggregated['MedPrice_sqft_tminus1'].str.get(0)

zip_aggregated['MedPrice_sqft_tminus2'] = Med_price_sqft_tminus2
zip_aggregated['MedPrice_sqft_tminus2'] = zip_aggregated['MedPrice_sqft_tminus2'].str.get(0)

zip_aggregated['MedPrice_sqft_tplus1'] = Med_price_sqft_tplus1
zip_aggregated['MedPrice_sqft_tplus1'] = zip_aggregated['MedPrice_sqft_tplus1'].str.get(0)

zip_aggregated

useful     funny      cool     Price   stars_1   stars_2  \
postal_code Years                                                               
15003       2008   2.000000  0.500000  2.000000  3.000000  0.000000  0.000000   
            2009   0.500000  0.000000  0.500000  2.000000  0.000000  0.000000   
            2010   1.625000  0.375000  0.375000  2.400000  0.000000  0.000000   
            2011   1.200000  0.200000  0.466667  2.400000  0.066667  0.000000   
            2012   1.800000  0.450000  0.800000  2.111111  0.150000  0.100000   
            2013   0.840000  0.560000  0.640000  1.888889  0.080000  0.120000   
            2014   0.764706  0.176471  0.205882  2.071429  0.058824  0.029412   
            2015   0.901639  0.327869  0.475410  2.076923  0.098361  0.049180   
            2016   0.319444  0.083333  0.194444  2.117647  0.041667  0.041667   
            2017   0.000000  0.000000  0.000000  2.666667  0.000000  0.250000   
15009       2014   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15012       2015   0.333333  0.000000  0.000000  1.000000  0.000000  0.000000   
15015       2011   1.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  0.500000  1.000000  1.500000  0.000000  0.000000   
            2013   0.000000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2014   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000   
            2015   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
            2016   0.500000  0.500000  0.000000  1.000000  0.500000  0.000000   
15017       2007   1.750000  0.250000  0.250000  1.750000  0.000000  0.000000   
            2008   0.666667  0.000000  0.000000  1.500000  0.000000  0.333333   
            2009   1.833333  1.166667  0.916667  1.818182  0.166667  0.250000   
            2010   1.074074  0.296296  0.296296  1.800000  0.074074  0.037037   
            2011   1.276316  0.434211  0.500000  1.650000  0.144737  0.078947   
            2012   1.239130  0.405797  0.318841  1.682540  0.137681  0.101449   
            2013   1.175214  0.337607  0.320513  1.814286  0.153846  0.145299   
            2014   0.977528  0.202247  0.288390  1.773810  0.198502  0.082397   
            2015   0.666667  0.139089  0.263789  1.773585  0.179856  0.103118   
            2016   0.536545  0.139535  0.272425  1.750000  0.191030  0.131229   
...                     ...       ...       ...       ...       ...       ...   
15321       2014   0.923077  0.115385  0.346154  2.000000  0.115385  0.038462   
            2015   2.903226  1.838710  2.516129  1.600000  0.032258  0.032258   
            2016   0.271186  0.016949  0.101695  1.714286  0.033898  0.016949   
            2017   0.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
15332       2006   1.000000  0.000000  0.000000  2.000000  0.000000  0.000000   
            2010   9.000000  3.000000  9.000000  2.000000  0.000000  0.000000   
            2011   1.500000  0.000000  1.000000  2.000000  0.000000  0.000000   
            2012   1.000000  0.428571  0.571429  2.000000  0.000000  0.000000   
            2013   0.875000  0.000000  0.125000  1.500000  0.250000  0.000000   
            2014   1.687500  0.375000  1.000000  1.750000  0.000000  0.062500   
            2015   0.360000  0.000000  0.120000  1.666667  0.080000  0.280000   
            2016   0.166667  0.000000  0.055556  1.571429  0.055556  0.166667   
            2017   0.000000  0.000000  0.000000  2.000000  1.000000  0.000000   
15339       2011   2.000000  0.500000  1.000000  2.000000  0.000000  0.000000   
            2012   0.000000  1.000000  0.000000  2.000000  0.000000  0.000000   
            2013   0.000000  0.500000  0.500000  2.000000  0.000000  0.500000   
            2014   0.000000  0.000000  0.000000  2.0

In [301]:
output_file = open("Feature_Matrix_complete.dat","wb")
pickle.dump(zip_aggregated, output_file)
output_file.close()

In [302]:
zip_aggregated.to_csv("Feature_Matrix_Yelp_Complete.csv")